package it.polimi.ingsw.controller;

import it.polimi.ingsw.exceptions.NoSpaceForStudentException;
import it.polimi.ingsw.exceptions.NoSuchStudentException;
import it.polimi.ingsw.messages.events.ChooseColorEvent;
import it.polimi.ingsw.messages.events.GameEventType;
import it.polimi.ingsw.messages.GameEvent;
import it.polimi.ingsw.model.CharacterCardEleven;
import it.polimi.ingsw.model.Player;

/**
 * This is the state generated by the card 11 ({@link it.polimi.ingsw.model.CharacterCardEleven}).
 * When a CHOOSE_COLOR event is received, it  three students of that color from each player entrance.
 *
 */
public class CharacterElevenState extends CharacterState{
    GameState nextState;
    CharacterCardEleven cc;
    public CharacterElevenState(RoundController context, int numberOfEvents, GameState nextState, CharacterCardEleven cc){
        super(context, numberOfEvents);
        this.nextState=nextState;
        this.cc=cc;
    }

    @Override
    public boolean checkValidEvent(GameEvent event) {
        return event.getEventType() == GameEventType.CHOOSE_COLOR;
    }


    @Override
    public void executeEvent(GameEvent event) throws NoSuchStudentException {
        ChooseColorEvent eventCast = (ChooseColorEvent) event;
        for(Player p: context.getSeatedPlayers()){
            for (int i =0; i<3;i++){

                try {
                    p.getSchool().getStudentsAtTables().moveStudentTo(eventCast.getColor(),context.gameManager.getBag());
                } catch (NoSpaceForStudentException ignored) {
                    //this was left empty on purpose. The card dictates to do nothing   if the player has n
                    // no more students of that color left
                }
            }
        }

        numberOfEvents--;
        context.changeState(nextState);
    }
}
